### ISSUE TITLE
Leverage Interpod affinity to deploy Snoopy operator pod

### ISSUE THREAD

**Issue by samira-barouti** [fennec-project/snoopy-operator#7]
Currently, Snoopy operator is leveraging `nodeSelector` to ensure snoopy pods and tenant application pods are deployed on the same node to facilitate the snoopy's access to the app pod's namespace. 

It is recommended to leverage Interpod affinity instead of node selector for this purpose. `InterPodAffinity` does not require the nodes to be labelled; instead the app's pods need to be labelled and the snoopy pods will leverage `PodAffinity` to be deployed on the same node as the app's pods.

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity

**Comment by acmenezes** [comment]
InterpodAffinity is calculated in during scheduling but it's expected to happen during the lifetime of the pod being inspected or targeted. And that not only that Pod's instance but also if it dies and gets restarted in the same or a different node. That requires the operator to stop the job change it and resume from the newly restarted pod. That said nodeSelector, that is also not enough for this feature, can be used during runtime to change nodes. In the end it doesn't seem to make much difference changing the approach to InterpodAffinity since the RequiredDuring runtime is not implemented. Only at scheduling time.

/close
